export const CAR_NUMBER_INPUT = 'CAR_NUMBER_INPUT'
export const CAR_PASSENGERS_INPUT = 'CAR_PASSENGERS_INPUT'
export const CAR_AGE_INPUT = 'CAR_AGE_INPUT'
export const CAR_BRAND_SELECT = 'CAR_BRAND_SELECT'
