export const UPLOAD_FILES_START = 'UPLOAD_FILES_START'
export const UPLOAD_FILES_SUCCESS = 'UPLOAD_FILES_SUCCESS'
export const UPLOAD_FILES_ERROR = 'UPLOAD_FILES_ERROR'
export const UPLOAD_FILES_INIT = 'UPLOAD_FILES_INIT'
